language: java
jdk: oraclejdk8
install : true
script: mvn -V clean jacoco:prepare-agent verify jacoco:report  -Djenkins.test.timeout=1000
after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/5173f3381d39108eb52e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always