name: 'Auto Assign PR'

on: pull_request_target

jobs:
  assign-pr:
    name: 'Auto Assign PR'
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
