name: 'Link Checker'

on: push

jobs:
  check-markdown-links:
    name: 'Check Markdown links'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: umbrelladocs/action-linkspector@v1.4.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          fail_on_error: true
          filter_mode: nofilter
          config_file: '.github/linkspector.yml'
          level: 'info'
